vich_uploader:
    db_driver: orm

    mappings:
        evenenemt_image:
            uri_prefix: /uploads/evenenemts
            upload_destination: '%kernel.project_dir%/public/uploads/evenements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
